app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.IndexMain.as_view()),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # 글 목록 조회
    path("", views.Index.as_view(), name='list'), 
    # 글 작성
    path("write/", views.Write.as_view(), name='write'),
    # 글 상세 조회
    path("<int:pk>/", views.DetailView.as_view(), name='detail'),
    # 글 수정
    path("edit/<int:pk>/", views.Update.as_view(), name='edit'),
    # 글 삭제
    path("delete/<int:pk>/", views.Delete.as_view(), name='delete'),
    # 글 검색
    path('search/', views.Search.as_view(), name='search'),
    # 댓글 작성
    path("<int:pk>/comment/write/", views.CommentWrite.as_view(), name='cm-write'),
    # 댓글 삭제
    path("comment/<int:pk>/delete/", views.CommentDelete.as_view(), name='cm-delete'),
]

blog/models.py
from django.db import models
from django.contrib.auth import get_user_model



User = get_user_model()

# Create your models here.
# 카테고리 필드
category_select = (
    ('자유', '자유'),
    ('취미', '취미'),
    ('정보', '정보'),
) 


# 게시글
class Post(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.CharField(max_length=30, choices= category_select, default='자유')
    created_at = models.DateTimeField(auto_now_add=True) 
    updated_at = models.DateTimeField(auto_now=True)
    is_deleted = models.BooleanField(default=False)
    hit = models.PositiveBigIntegerField(default=0)
    head_image = models.ImageField(
        upload_to='blog/images/%Y/%m/%d/', blank=True)
    file_upload = models.FileField(
        upload_to='blog/files/%Y/%m/%d/', blank=True)

    @property
    def update_counter(self):
        self.hit = self. hit + 1
        self.save()

    def get_file_name(self):
        return self.file_upload.name.split('/')[-1]

    def get_file_ext(self):
        return self.get_file_name().split('.')[-1]
    
# 댓글
class Comment(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.content

blog/forms.py
from django import forms
from .models import Post, Comment


# 게시글 폼
class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['category','title', 'content', 'file_upload', 'head_image']
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'write-title',
                'id': 'board-title'
            }),
            'content': forms.Textarea(attrs={
                'class': 'write-content',
                'id': 'board-content'
            }) ,
            'category': forms.Select(attrs={
                'class': 'write-category',
                'id': 'category'
            }),
            'file_upload': forms.FileInput(attrs={
                'class': 'file_upload'
             }
            )
        }
        


# 댓글 폼
class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={    'class':'cm-write'})
        }


# 검색 폼
class PostSearchForm(forms.Form):
    search_word = forms.CharField(label='search_Word')

blog/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
from .models import Post, Comment
from .forms import PostForm, CommentForm
# Create your views here.


class Index(View):
    def get(self, request):
        post_objs = Post.objects.all().order_by('-created_at')
        cnt = Post.objects.count()
        context = {
            'posts': post_objs,
            'cnt': cnt
        }
        return render(request, 'blog/post_list.html', context)
    

# 게시글 작성
class Write(LoginRequiredMixin, View):
    def get(self, request):
        form = PostForm()
        context = {
            'form': form,
        }
        return render(request, 'blog/post_form.html', context)

    def post(self, request):
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.writer = request.user
            post.save()
            return redirect('blog:list')
        context = {
            'form': form
        }
        return render(request, 'blog/post_form.html')


# 게시글 상세보기
class DetailView(View):
    def get(self, request, pk): 
        try:
            post = Post.objects.get(pk=pk)
        except ObjectDoesNotExist as e:
            return render(request, 'blog/deleted_post.html')
        comments = Comment.objects.filter(post=post)
        comment_form = CommentForm()
        context = {
            'post': post,
            'comments': comments,
            'comment_form': comment_form,
        }
        post.update_counter

        return render(request, 'blog/post_detail.html', context)
    

# 게시글 수정
class Update(View):
    def get(self, request, pk): 
        post = Post.objects.get(pk=pk)
        form = PostForm(initial={'title': post.title, 'content': post.content, 'category': post.category})
        context = {
            'form': form,
            'post': post
        }
        return render(request, 'blog/post_edit.html', context)

    def post(self, request, pk):
        post = Post.objects.get(pk = pk)
        form = PostForm(request.POST, request.FILES ,instance=post)
        if form.is_valid():
            post.category = form.cleaned_data['category']
            post.title = form.cleaned_data['title']
            post.content = form.cleaned_data['content']
            post.save()
            return redirect('blog:detail', pk=pk)

        form.add_error(None,'폼이 유효하지 않습니다.')
        context = {
            'form': form
        }
        
    

# 게시글 삭제
class Delete(View):
    def post(self, request, pk): 
        post = Post.objects.get(pk=pk)
        post.delete()
        return redirect('blog:list')
    

# 게시글 검색
class Search(View):
    def get(self, request):
        search_word = request.GET.get('search_word')
        category = request.GET.get('category') 
        posts = Post.objects.all().order_by('created_at')
        sort = request.GET.get('sort', 'latest')

        if search_word:
            posts = posts.filter(Q(title__icontains=search_word) | Q(category__icontains=search_word))

        if category:
            posts = posts.filter(category=category)

        if sort == 'hits':
            posts = posts.order_by('-hit')  
        else:
            posts = posts.order_by('-created_at')  

        context = {
            'posts': posts,
            'search_word': search_word,
            'category': category,
            'sort': sort  
        }
        return render(request, 'blog/post_search.html', context)
    

# 댓글 작성
class CommentWrite(View):
    def post(self, request, pk):
        form = CommentForm(request.POST)
        post = Post.objects.get(pk=pk)
        if form.is_valid():
            content = form.cleaned_data['content']
            writer = request.user
            comment = Comment.objects.create(post=post, content=content, writer=writer)
            return redirect('blog:detail', pk=pk)

        context = {
            'post': post,
            'comments': post.comment_set.all(),
            'comment_form': form
        }
        return render(request, 'blog/post_detail.html', context)
    

# 댓글 삭제
class CommentDelete(View):
    def post(self, request, pk):
        comment = Comment.objects.get(pk=pk)
        post_id = comment.post.id
        comment.delete()

        return redirect('blog:detail', pk = post_id)

blog/templates/blog/deleted_post.html
{% extends 'base.html' %}
{% block content %}
<h1><존재하지 않는 게시글 입니다.></h1>
<h2><a href="{% url 'blog:list' %}">목록으로 돌아가기</a></h2>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="main">

    <h2 class="main-title">글 조회</h2>

   <div class="view">
        <div class="view-header">
            <h2>{{ post.title }}</h2>
            
            <!-- 글 상세화면 -->
            <div class="view-info">
                <p>카테고리: {{ post.category }} |</p>
                <p>작성자: {{ post.writer }} |</p>
                <p>작성일: {{ post.created_at|date:'Y-m-d H:m' }} |</p>
                <p>조회수: {{ post.hit }} </p>
            </div>
        </div>
        <div class="view-content">
            {{ post.content }}
            {% if post.file_upload %}
            <img src="{{ post.file_upload.url }}" width="900px">
            {% endif %}
        </div>
   </div>
    
    <div class="btn-group">
        <a href="{% url 'blog:list' %}" class="btn">목록</a>
        {% if post.writer == request.user %}
            <a href="{% url 'blog:edit' pk=post.pk %}" class="btn">수정</a>
            <form action="{% url 'blog:delete' pk=post.pk %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn">삭제</button>
            </form>
            {% endif %}
    </div>
</div>

<!-- 댓글 -->
<div class="main">

    <h2 class="main-title">댓글</h2>
    {% if comments %}
    <ul class="cm-ul">
        {% for comment in comments %}
        <li>
            <div class="cm-header">
                <div class="view-info">
                    <p>{{ comment.writer }}({{ comment.created_at|date:'Y-m-d H:m'}})</p>
                    {% if comment.writer == request.user %}
                    <form action="{% url 'blog:cm-delete' pk=comment.pk %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="cm-delete">X</button>
                    </form>
                    {% endif %}
                </div>
                <h3>{{ comment.content }} </h3>
            </div>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>댓글이 없습니다.</p>
    {% endif %}
    
    <!-- 댓글 작성 -->
    <form action="{% url 'blog:cm-write' pk=post.pk %}" method="post">
        {% csrf_token %}
        {{ comment_form.content }}
        <div class="btn-group">
                <button type="submit" class="btn">작성</button>
            </div>
            </form>
</div>

{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'base.html' %}

{% block content %}
<div class="main">
    <h2 class="main-title">글수정</h2>
    <table class="table write">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <tr>
                <th><label for="category">카테고리</label></th>
                <td>
                    <select id="category" name="{{ form.category.name }}">
                        {% for choice in form.category.field.choices %}
                            <option value="{{ choice.0 }}" {% if choice.0 == form.initial.category %}selected{% endif %}>{{ choice.1 }}</option>
                        {% endfor %}
                    </select>
                </td>
            </tr>
            <tr>
                <th><label for="board-title">제목</label></th>
                <td><input type="text" id="board-title" name="{{ form.title.name }}" value="{{ form.initial.title }}"></td>
            </tr>
            <tr>
                <th><label for="board-content">내용</label></th>
                <td><textarea name="{{ form.content.name}}" id="board-content">{{ form.initial.content }}</textarea></td>
            </tr>
            <tr>
                <th><label for="board-content">사진</label></th>
                <td><input type="file" id="file_upload" name="{{ form.file_upload.name }}" value="{{ form.initial.file_upload }}"></td>
            </tr>
    </table>
        <div class="btn-group">
            <button type="submit" class="btn">수정</button>
        </div>
    </form>
</div>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="main">
        <h2 class="main-title">글쓰기</h2>
        <p class="main-desc">내용을 입력 해주세요.</p>
        <form action="{% url 'blog:write' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <form>
                <table class="table write">
                  <colgroup>
                    <col style="width: 120px">
                    <col>
                  </colgroup>
                  <tbody>
                    <tr>
                      <th><label for="category">카테고리</label></th>
                      <td>
                        {{ form.category }}
                      </td>
                    </tr>
                    <tr>
                      <th><label for="board-title">제목</label></th>
                      <td>{{ form.title }}</td>
                    </tr>
                    <tr>
                      <th><label for="board-content">내용</label></th>
                      <td>
                        {{ form.content }}
                      </td>
                    </tr>
                    <tr>
                      <th><label for="board-content">사진</label></th>
                      <td>
                        {{ form.file_upload }}
                      </td>
                    </tr>
                </tbody>
                </tbody>
            </table>
            <div class="btn-group">
                <button type="submit" class="btn">작성</button>
            </div>
        </form>
    </div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="main">
    <h2 class="main-title">블로그 게시판</h2>
    
    <!-- 게시글 리스트 -->
    {% if posts %}
    <div class="board-top">
        <p class="main-desc"><strong>{{ cnt }}개</strong>의 게시글이 있습니다.</p>   

        <!-- 검색 폼 -->
        <div>
            <form action="{% url 'blog:search' %}" method="GET" class="search-form">
                <label for="category" class="a11y-hidden">카테고리</label>
                <select name="category" id="category">
                    <option value="자유">자유</option>
                    <option value="취미">취미</option>
                    <option value="정보">정보</option>
                </select>
                <label for="search" class="a11y-hidden">검색</label>
                <input id="search" type="text" name="search_word" placeholder="검색어를 입력하세요">
                <button type="submit"><img src="{% static 'img/icon-search.png' %}" alt="검색"></button>
                <label for="sort" class="a11y-hidden">정렬</label>
                <select name="sort" id="sort">
                    <option value="latest" {% if sort_by == 'latest' %}selected{% endif %}>최신순</option>
                    <option value="hits" {% if sort_by == 'hits' %}selected{% endif %}>조회순</option>
                </select>
            </form>
        </div>
    </div>
    
    
    <table class="table list">
        <colgroup>
            <col style="width: 100px" />
            <col />
            <col style="width: 150px" />
            <col style="width: 120px" />
            <col style="width: 100px" />
        </colgroup>
        <thead>
            <tr>
                <th>카테고리</th>
                <th>제목</th>
                <th>작성자</th>
                <th>작성일</th>
                <th>조회수</th>
            </tr>
        </thead>
        <tbody>
            {% for post in posts %}
            <tr>
                <td>{{ post.category }}</td>
                <td><a href="{% url 'blog:detail' pk=post.pk %}" >{{ post.title }}</a></td>
                <td>{{ post.writer }}</td>
                <td>{{ post.created_at|date:"Y-m-d" }}</td>
                <td>{{ post.hit }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>작성된 게시물이 없습니다.</p>
    {% endif %}
    
    <!-- 글 작성 버튼 -->
    <div class="btn-group">
        <form action="{% url 'blog:write' %}" method="get">
            <input type="hidden" name="{{ redirect_field_name }}" value="{{ request.GET.next }}">
            <button type="submit" class="btn">글 작성</button>
        </form>
    </div>
</div>
    
    {% endblock %}

blog/templates/blog/post_search.html
{% extends 'base.html' %}

{% block content %}
  {% if posts %}
    <div class="main">
        <h2 class="main-title">검색 결과</h2>
        <table class="table list">
            <colgroup>
                <col style="width: 100px" />
                <col />
                <col style="width: 150px" />
                <col style="width: 120px" />
                <col style="width: 100px" />
            </colgroup>
            <thead>
                <tr>
                    <th>카테고리</th>
                    <th>제목</th>
                    <th>작성자</th>
                    <th>작성일</th>
                    <th>조회수</th>
                </tr>
            </thead>
            <tbody>
                {% for post in posts %}
                <tr>
                    <td>{{ post.category }}</td>
                    <td><a href="{% url 'blog:detail' pk=post.pk %}" >{{ post.title }}</a></td>
                    <td>{{ post.writer }}</td>
                    <td>{{ post.created_at|date:"Y-m-d" }}</td>
                    <td>{{ post.hit }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
      {% else %}
        <p>검색 결과가 없습니다.</p>
      {% endif %}
    </div>
{% endblock %}