app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.IndexMain.as_view()),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    # user/
    # 회원가입
    path('register/', views.Registration.as_view(), name='register'),
    # 로그인
    path('login/', views.Login.as_view(), name='login'),
    # 로그아웃
   path('logout/', views.Logout.as_view(), name='logout'),
   # 비밀번호 변경
   path('changepw/', views.ChangePassword.as_view(), name='changepw')
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils import timezone

# Create your models here.


class UserManager(BaseUserManager):
    
    def _create_user(self, email, password, is_staff, is_superuser, **extra_fields):
        if not email:
            raise ValueError('User must have an email')
        now = timezone.now() 
        email = self.normalize_email(email)
        user = self.model(
            email=email,
            is_staff=is_staff,
            is_active=True,
            is_superuser=is_superuser,
            last_login=now,
            date_joined=now,
            **extra_fields
        )
        user.set_password(password) 
        user.save(using=self._db) 
        return user
    # create_user
    def create_user(self, email, password, **extra_fields):
        return self._create_user(email, password, False, False, **extra_fields)
    # create_superuser
    def create_superuser(self, email, password, **extra_fields):
        return self._create_user(email, password, True, True, **extra_fields)
    
    
class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, max_length=255)
    name = models.CharField(max_length=50, null=True, blank=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    last_login = models.DateTimeField(null=True, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    
    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = []
    
    objects = UserManager()


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    nickname = models.CharField(max_length=10)

user/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
# from .models import User
from django.contrib.auth import get_user_model


User = get_user_model()


class RegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['email']


class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['email', 'password']

user/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash 
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from .forms import RegisterForm, LoginForm
# Create your views here.


# 회원가입
class Registration(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('blog:list')
        form = RegisterForm()
        context = {
            'form': form,
        }
        return render(request, 'user/user_register.html', context)

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect('user:login')


# 로그인
class Login(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('blog:list')
        
        form = LoginForm()
        context = {
            'form': form,
        }
        return render(request, 'user/user_login.html', context)
        
    def post(self, request):
        if request.user.is_authenticated:
            return redirect('blog:list')
        
        form = LoginForm(request, request.POST)
        if form.is_valid():
            email = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=email, password=password) 
            
            if user:
                login(request, user)
                return redirect('blog:list')
            
        form.add_error(None, '아이디가 없습니다.')
        
        context = {
            'form': form
        }
        
        return render(request, 'user/user_login.html', context)
    
    
# 로그아웃
class Logout(View):
    def get(self, request):
        logout(request)
        return redirect('blog:list')
    

# 비밀번호 변경
class ChangePassword(View):
    def get(self, request):
        form = PasswordChangeForm(request.user)
        context = {
            'form': form,
        }
        return render(request, 'user/change_password.html', context)
    
    def post(self, request):
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, '비밀번호가 성공적으로 변경되었습니다.')
            return redirect('user:logout', pk=request.user.pk)
        else:
            messages.error(request, '비밀번호 변경에 실패했습니다. 다시 시도해주세요.')
        
        context = {
            'form': form
        }
        
        return render(request, 'user/change_password.html', context)

user/templates/user/change_password.html
{% extends "base.html" %}

{% block content %}
<div class="main">
  <div class="container">
    <h2 class="title">비밀번호 변경</h2>
    <ul class="description">
        <li>다른 개인 정보와 유사한 비밀번호는 사용할 수 없습니다.
        </li>
        <li>비밀번호는 최소 8자 이상이어야 합니다.</li>
        <li>통상적으로 자주 사용되는 비밀번호는 사용할 수 없습니다.</li>
        <li>숫자로만 이루어진 비밀번호는 사용할 수 없습니다.</li>
      </ul>
      <form method="post" action="{% url 'user:changepw' %}" class="login">
        {% csrf_token %}
        <div>
          <label class="label-width" for="id_old_password">기존 비밀번호</label>
          <input type="password" id="id_old_password" name="{{ form.old_password.name }}" value="{{ form.initial.old_password }}" required autocomplete="current-password">
        </div>
        <div>
          <label class="label-width" for="id_new_password1">새 비밀번호</label>
          <input type="password" id="id_new_password1" name="{{ form.new_password1.name }}" value="{{ form.initial.new_password1 }}" required autocomplete="current-password">
        </div>
        <div>
          <label class="label-width" for="id_new_password2">새 비밀번호 확인</label>
          <input type="password" id="id_new_password2" name="{{ form.new_password2.name }}" value="{{ form.initial.new_password2 }}" required autocomplete="current-password">
        </div>
        <button type="submit" class="submit-button">비밀번호 변경</button>
      </form>
    </div>
  </div>
{% endblock %}

user/templates/user/user_login.html
{% extends "base.html" %}

{% block content %}
<div class="main">
    <div class="container">
        <h2 class="title">로그인</h2>
        <p class="description">아이디와 비밀번호를 입력하고 로그인 하세요</p>
        <form action="{% url 'user:login' %}" method="post" class="login">
            {% csrf_token %}
            <div>
                <label class="label-width" for="user-id">아이디</label>
                <input type="email" id="user-id" name="{{ form.username.name }}" value="{{ form.initial.username }}">
              </div>
              <div>
                <label class="label-width" for="user-pw">비밀번호</label>
                <input type="password" id="user-pw" name="{{ form.password.name }}" value="{{ form.initial.password }}" required>
              </div>
            <button type="submit" class="submit-button">로그인</button>
        </form>
    </div>
</div>

{% endblock %}

user/templates/user/user_register.html
{% extends "base.html" %}

{% block content %}
<div class="main">
    <div class="container">
        <h2 class="title">회원가입</h2>
        <ul class="description">
            <li>다른 개인 정보와 유사한 비밀번호는 사용할 수 없습니다.
            </li>
            <li>비밀번호는 최소 8자 이상이어야 합니다.</li>
            <li>통상적으로 자주 사용되는 비밀번호는 사용할 수 없습니다.</li>
            <li>숫자로만 이루어진 비밀번호는 사용할 수 없습니다.</li>
          </ul>
        <form action="{% url 'user:register' %}" method="post" class="login">
            {% csrf_token %}
            <div>
                <label class="label-width" for="id_email">아이디</label>
                <input type="email" id="id_email" name="{{ form.email.name }}" value="{{ form.initial.email }}">
              </div>
              <div>
                <label class="label-width" for="id_password1">비밀번호</label>
                <input type="password" id="id_password1" name="{{ form.password1.name }}" value="{{ form.initial.password1 }}" required autocomplete="new-password">
              </div>
              <div>
                <label class="label-width" for="id_password2">비밀번호 확인</label>
                <input type="password" id="id_password1" name="{{ form.password2.name }}" value="{{ form.initial.password2 }}" required autocomplete="new-password">
            </div>
            <p class="description">이전과 동일한 비밀번호를 입력하세요.</p>
            <button type="submit" class="submit-button">회원가입</button>
        </form>
    </div>
</div>
{% endblock %}