app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.IndexMain.as_view()),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # 글 목록 조회
    path("", views.Index.as_view(), name='list'), 
    # 글 작성
    path("write/", views.Write.as_view(), name='write'),
    # 글 상세 조회
    path("<int:pk>/", views.DetailView.as_view(), name='detail'),
    # 글 수정
    path("edit/<int:pk>/", views.Update.as_view(), name='edit'),
    # 글 삭제
    path("delete/<int:pk>/", views.Delete.as_view(), name='delete'),
    # 글 검색
    path('search/', views.Search.as_view(), name='search'),
    # 댓글 작성
    path("<int:pk>/comment/write/", views.CommentWrite.as_view(), name='cm-write'),
    # 댓글 삭제
    path("comment/<int:pk>/delete/", views.CommentDelete.as_view(), name='cm-delete'),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    # user/
    # 회원가입
    path('register/', views.Registration.as_view(), name='register'),
    # 로그인
    path('login/', views.Login.as_view(), name='login'),
    # 로그아웃
   path('logout/', views.Logout.as_view(), name='logout'),
   # 비밀번호 변경
   path('changepw/', views.ChangePassword.as_view(), name='changepw')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/table.css' %}">
    <link rel="stylesheet" href="{% static 'css/common.css' %}">
    <link rel="stylesheet" href="{% static 'css/list.css' %}">
    <link rel="stylesheet" href="{% static 'css/view.css' %}">
    <link rel="stylesheet" href="{% static 'css/write.css' %}">
    <link rel="stylesheet" href="{% static 'css/comment.css' %}">
    <link rel="stylesheet" href="{% static 'css/login-join.css' %}">
    <title>
        취미 블로그
    </title>
</head>
<body>
    <div class="header">
        <a href="{% url 'blog:list' %}" ><h1>Blog</h1></a>
        <div class="sub-header">
            {% if user.is_authenticated %}
            <p>Welcome, {{ user.email }}</p>
            <a href="{% url 'user:changepw' %}">비밀번호 변경</a>
            <a href="{% url 'user:logout' %}">로그아웃</a>
            {% else %}
            <p>Please, Login</p>
            <a href="{% url 'user:login' %}" >로그인</a>
            <a href="{% url 'user:register' %}" >회원가입</a>
            {% endif %}
        </div>
    </div>
        {% block content %}
        {% endblock %}
    <!-- footer -->
  <p class="footer">Copyright 2023. Seong All rights reserved.</p>
  <!-- //footer -->
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="header-click">
        <a href="{% url 'blog:list' %}" >블로그 입장</a>
        <a href="{% url 'user:register' %}" >회원가입</a>
        <a href="{% url 'user:login' %}" >로그인</a>
    </div>
{% endblock %}